apiVersion: v1
kind: Pod
metadata:
  name: iperfonubtest
spec:
  containers:
  - name: server
    image: sheenam3/iperf3on18.04
    command: ["/bin/sh", "-c"]
    args:
      - ./root/scripts/server.sh;
        sleep 900000;
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
      - mountPath: /root/scripts
        name: host-script
  - name: client1
    image: sheenam3/iperf3on18.04
    command: ["/bin/sh","-c"]
    args:
      - sleep 9000;
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
      - mountPath: /root/scripts
        name: host-script
  volumes:
    - name: host-script
      hostPath:
        path: /root/scripts
